;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Trine Enchanted Edition
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     5.0.0
; Xidi Form:        DInput8
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          samuelgr
; Last Modified:    05/31/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


[Mapper]
Type            = TrineEnchantedEdition


[CustomMapper:TrineEnchantedEdition]
Template = StandardGamepad

; Face button rearrangement
ButtonA = Button(2)
ButtonB = Button(3)
ButtonX = Button(1)
ButtonY = Button(4)

; Shield (Knight), Bow (Thief), and Magic (Wizard) set up on right stick
StickRightX = Axis(Z)
StickRightY = Invert(Axis(RotX))
