;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Trine 2 - Complete Story
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     5.0.0
; Xidi Form:        DInput8
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          samuelgr
; Last Modified:    07/02/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


[Mapper]
; This game cannot have perfect compatibility between all the in-game prompts and the controller, without in-game remapping.
; Several mappers are therefore defined in this file, all available for user selection.
Type            = Trine1and2Hybrid


[CustomMapper:TrineCommon]
Template        = StandardGamepad

; Shield (Knight), Bow (Thief), and Magic (Wizard) set up on right stick
StickRightX     = Axis(Z)
StickRightY     = Invert(Axis(RotX))

; Skills menu on LS instead of back
ButtonBack      = Button(11)
ButtonLS        = Button(9)


[CustomMapper:Trine1]
; For perfect compatibility with the colored menu prompts and Trine 1.
; Neither face nor shoulder buttons match the in-game controller tutorials.
Template        = TrineCommon

; Face button rearrangement
ButtonA         = Button(2)
ButtonB         = Button(3)
ButtonX         = Button(1)
ButtonY         = Button(4)


[CustomMapper:Trine2]
; For perfect compatibility with the in-game controller tutorials.
; Face buttons do not match the colored menu prompts.
Template        = TrineCommon

; Shoulder button rearrangement
TriggerLT       = Button(5)
TriggerRT       = Button(6)
ButtonLB        = Button(7)
ButtonRB        = Button(8)


[CustomMapper:Trine1and2Hybrid]
; For perfect compatibility with the colored menu prompts and shoulder button in-game controller tutorials.
; Face buttons do not match the in-game controller tutorials.
Template        = TrineCommon

; Face button rearrangement
ButtonA         = Button(2)
ButtonB         = Button(3)
ButtonX         = Button(1)
ButtonY         = Button(4)

; Shoulder button rearrangement
TriggerLT       = Button(5)
TriggerRT       = Button(6)
ButtonLB        = Button(7)
ButtonRB        = Button(8)
